### ISSUE TITLE
Rewrite/Revise LICENSE for TeamGalacticraft and Galacticraft-Fabric

### ISSUE THREAD

**Issue by JoeZwet** [StellarHorizons/Galacticraft-Rewoven#6]
The current license is for the original Galacticraft project this needs to be updated before release.

**Comment by SebaSphere** [comment]
@vos6434 assigned me and you to help write a updated license.

**Comment by marcus8448** [comment]
Shouldn't @micdoodle8 have a say too?

**Comment by SebaSphere** [comment]
Ye good idea @marcus8448

**Comment by coderbot16** [comment]
Why not just use a standard license like LGPLv3 / MIT / CC4? The only reason for the current license appears to be as a futile attempt to stop mod repost sites, which do not care about copyright in the first place - as most sites are located in Vietnam/China/Russia where US copyright law is null and void. 

Some associated criticisms/issues:
 * The code part of §5 would could be managed through a CLA
 * On account of §28e the license isn't even open source! 
 * §29 doesn't appear to understand how the GPL actually works.
 * §35 is a further term that makes the license not open source, because it gives the developers the right to assign a more restrictive license in the future.

In its current state, Galacticraft (and Galacticraft-Fabric) are not really open source projects, but rather shared source projects.

**Comment by marcus8448** [comment]
I would agree that we should use LGPLv3 / MIT / CC4 / etc. But I do think that we should (at least) have something about redistribution. Yes, US copyright law is nothing in other countries, but at least large search engines are in the US. This means that we can at least stop google/others from indexing that page, causing to be downloaded from there less.

**Comment by coderbot16** [comment]
The main consideration on redistribution restrictions is whether the benefits (reduced amount of mod repost instances) outweigh the costs (impacting legitimate users with restrictions). For me personally I doubt that the benefits in regards to blocking mod repost sites are very great - it takes large amounts of effort to get the mods actually removed, and it's a constant struggle to constantly scan for new repost sites, as there are thousands in existence. In most cases, the curseforge page rises to the top of the results anyway, so users would have to actively seek for repost sites.

Also, correct me if I'm wrong, but the following line expressly prohibits modifications of the LGPLv3 license:
`Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.`

**Comment by micdoodle8** [comment]
I don't use curseforge, so it's not guaranteed that people will find the correct homepage with a search. Historically, we had issues with mod repost sites showing higher than my site on google right after a new version release. So blocking mod repost sites is an option I like to have. Although I didn't write the license, I also don't see what restrictions are being placed on end-users. I've yet to receive a complaint about the license.

**Comment by coderbot16** [comment]
With regards to potential restrictions, while the current license is relatively unrestrictive with regards to an end user / modpack context, its restrictions regarding redistributions of binaries also prohibit full forks of the project.

However, if truly necessary, then an option would be to use the CC-BY-NC-SA license, to prohibit commerical usage (such as adfly links) used by mod repost sites. Of course, this would apply to everyone, which would mean that if you wanted ad rev you would need a CLA granting you the rights to distribute the mod commercially.

**Comment by JoeZwet** [comment]
License updated to MIT.
